### ISSUE TITLE
Watch for openings between times

### ISSUE THREAD

**Issue by sdotz** [lgrees/resy-cli#1]
Hey there. This looks really good so far. It seems to be designed for restaurants that open slots in advance, but I wonder if it can be adapted to watch for openings and snipe them given some parameters.

I find most of my bookings by checking back constantly as people tend to cancel within days or hours of the rez. The resy notify functionality is usually too late (or I'm too slow).

For example, I'd like to get a table for 6 at popular restaurant XYZ between 5pm and 9pm. I'd like to be able to watch for openings and book one within the params as soon as it appears.

Wondering your thoughts, and happy to help!

**Comment by lgrees** [comment]
Hey! Sorry just now responding - I don't have notifications configured on gh. Thanks for taking a look at the app.

I avoided the use-case that you mentioned because I didn't want to deal with any kind of long-running polling process. Just wanted to handle my simple "book ahead of time" use-case.

It probably wouldn't be too hard to extend this code to attempt a booking within the provided params on a recurring basis up until the booking by adding a cron job or something. I unfortunately haven't had a lot  of time to work on this project (was more just a fun way for me to learn Go), but happy to bounce ideas.
